services:
  postgres:
    image: postgres:16
    container_name: chargetrackr-postgres
    environment:
      POSTGRES_DB: changetrackr
      POSTGRES_USER: changetrackr
      POSTGRES_PASSWORD: changetrackr
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: chargetrackr-redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: chargetrackr-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
