<!doctype html>
<html lang="en"><head><meta charset="utf-8"><style>
@page { margin: 72px 42px 52px; } * { box-sizing: border-box; } body { margin: 0; color: #1c3027; font-family: DejaVu Sans, sans-serif; font-size: 10px; line-height: 1.5; }
header { position: fixed; top: -52px; left: 0; right: 0; height: 38px; border-bottom: 2px solid #14975e; } .brand { float: left; color: #117a4d; font-size: 16px; font-weight: bold; } .brand b { margin-right: 6px; padding: 4px 7px; border-radius: 5px; color: #fff; background: #14975e; } .org { float: right; color: #68786f; font-size: 8px; text-align: right; }
footer { position: fixed; bottom: -34px; left: 0; right: 0; padding-top: 7px; border-top: 1px solid #dfe9e3; color: #7a8981; font-size: 7px; } footer span { float: right; } footer span:after { content: counter(page); }
.eyebrow { color: #138454; font-size: 8px; font-weight: bold; letter-spacing: 1px; text-transform: uppercase; } h1 { margin: 5px 0 7px; color: #183329; font-size: 22px; line-height: 1.2; } .summary { margin: 0 0 15px; color: #65776d; font-size: 10px; } .status { display: inline-block; margin-bottom: 16px; padding: 5px 10px; border-radius: 12px; color: #0f7649; background: #e6f7ed; font-size: 8px; font-weight: bold; text-transform: uppercase; }
.facts { width: 100%; margin-bottom: 18px; border-collapse: collapse; } .facts td { width: 25%; padding: 9px 10px; border: 1px solid #e0e9e4; vertical-align: top; } .facts small { display: block; margin-bottom: 3px; color: #7b8982; font-size: 7px; text-transform: uppercase; } .facts strong { font-size: 9px; }
h2 { margin: 17px 0 8px; color: #1d392d; font-size: 13px; } .section { margin-bottom: 9px; padding: 11px 13px; border-left: 3px solid #6f48d8; background: #faf8ff; page-break-inside: avoid; } .section h3 { margin: 0 0 5px; color: #44268c; font-size: 10px; } .section p { margin: 0; white-space: pre-line; }
.timeline { width: 100%; border-collapse: collapse; } .timeline td { padding: 8px; border-bottom: 1px solid #e4ebe7; vertical-align: top; } .timeline .date { width: 112px; color: #75847c; font-size: 8px; } .timeline strong { display: block; } .timeline small { color: #7b8982; }
.photos { width: 100%; } .photo { display: inline-block; width: 47%; margin: 0 2% 12px 0; vertical-align: top; page-break-inside: avoid; } .photo img { width: 100%; height: 155px; border-radius: 5px; object-fit: cover; } .photo strong { display: block; margin-top: 5px; color: #168451; font-size: 8px; } .photo span { color: #6f7f76; font-size: 8px; }
</style></head><body>
<header><div class="brand"><b>CT</b>ChargeTrackr</div><div class="org">{{ $organization }}<br>{{ $generatedAt }}</div></header>
<footer>Confidential operational document<span>Page </span></footer>
<main><div class="eyebrow">{{ $document['eyebrow'] }}</div><h1>{{ $document['title'] }}</h1><p class="summary">{{ $document['summary'] }}</p><span class="status">{{ $document['status'] }}</span>
<table class="facts">@foreach(array_chunk($document['facts'], 4, true) as $factRow)<tr>@foreach($factRow as $label => $value)<td><small>{{ $label }}</small><strong>{{ $value ?: '-' }}</strong></td>@endforeach @for($i = count($factRow); $i < 4; $i++)<td></td>@endfor</tr>@endforeach</table>
@foreach($document['sections'] as $section)<div class="section"><h3>{{ $section['title'] }}</h3><p>{{ $section['body'] }}</p></div>@endforeach
@if(count($document['timeline']))<h2>Activity timeline</h2><table class="timeline">@foreach($document['timeline'] as $event)<tr><td class="date">{{ $event['date'] }}</td><td><strong>{{ $event['title'] }}</strong>{{ $event['description'] }}<br><small>{{ $event['actor'] }}</small></td></tr>@endforeach</table>@endif
@if(count($document['photos'] ?? []))<h2>Photographic evidence</h2><div class="photos">@foreach($document['photos'] as $photo)<div class="photo"><img src="{{ $photo['data'] }}"><strong>{{ $photo['phase'] }}</strong><span>{{ $photo['caption'] }}</span></div>@endforeach</div>@endif
</main></body></html>
