<!doctype html><html lang="en"><head><meta charset="utf-8"><style>
@page { margin: 38px; } * { box-sizing: border-box; } body { margin: 0; color: #1d3027; font-family: DejaVu Sans, sans-serif; font-size: 10px; } .top { padding: 22px 25px; border-radius: 8px; color: #fff; background: #15975e; } .brand { font-size: 19px; font-weight: bold; } .brand b { margin-right: 7px; padding: 4px 7px; border-radius: 5px; color: #15975e; background: #fff; } .receipt-title { float: right; margin-top: -22px; text-align: right; } .receipt-title strong { display: block; font-size: 14px; } .receipt-title span { font-size: 8px; opacity: .82; } h1 { margin: 26px 0 5px; font-size: 24px; } .paid { display: inline-block; padding: 5px 10px; border-radius: 12px; color: #0e7749; background: #e4f7ec; font-size: 8px; font-weight: bold; text-transform: uppercase; } .amount { margin: 20px 0; padding: 18px; border: 1px solid #dce8e1; border-radius: 7px; background: #f7fbf8; text-align: center; } .amount small { display: block; color: #77867e; text-transform: uppercase; } .amount strong { display: block; margin-top: 5px; color: #117a4d; font-size: 28px; } .grid { width: 100%; margin: 18px 0; border-collapse: collapse; } .grid td { width: 50%; padding: 11px 12px; border: 1px solid #e2eae6; } .grid small { display: block; margin-bottom: 4px; color: #78877f; font-size: 7px; text-transform: uppercase; } .grid strong { font-size: 10px; } h2 { margin: 22px 0 9px; font-size: 14px; } .line { width: 100%; border-collapse: collapse; } .line th { padding: 9px; color: #fff; background: #263d32; font-size: 8px; text-align: left; } .line td { padding: 9px; border-bottom: 1px solid #e2eae6; } .line .right { text-align: right; } .total td { color: #117a4d; font-size: 12px; font-weight: bold; } .note { margin-top: 28px; padding: 12px; border-left: 3px solid #7548dc; color: #5f6f67; background: #faf8ff; font-size: 8px; } footer { position: fixed; bottom: 0; left: 0; right: 0; padding-top: 9px; border-top: 1px solid #dfe8e3; color: #7b8982; font-size: 7px; text-align: center; }
</style></head><body>
<div class="top"><div class="brand"><b>CT</b>ChargeTrackr</div><div class="receipt-title"><strong>Payment receipt</strong><span>{{ $payment->reference }}</span></div></div>
<h1>Charging payment</h1><span class="paid">{{ $payment->status }}</span><div class="amount"><small>Amount {{ $payment->status === 'paid' ? 'paid' : 'recorded' }}</small><strong>{{ number_format($payment->amount_millimes / 1000, 3) }} {{ $payment->currency }}</strong></div>
<table class="grid"><tr><td><small>Customer</small><strong>{{ $payment->user?->name }}</strong><br>{{ $payment->user?->email }}</td><td><small>Charging network</small><strong>{{ $payment->organization?->name }}</strong><br>{{ $payment->organization?->contact_email }}</td></tr><tr><td><small>Payment method</small><strong>{{ str_replace('_', ' ', ucfirst($payment->method)) }}</strong><br>{{ $payment->provider }}</td><td><small>Transaction reference</small><strong>{{ $payment->provider_transaction_id ?: 'Pending' }}</strong><br>{{ $payment->paid_at?->format('d M Y, H:i') ?? $payment->created_at?->format('d M Y, H:i') }}</td></tr></table>
<h2>Charging details</h2><table class="line"><thead><tr><th>Description</th><th>Detail</th><th class="right">Amount</th></tr></thead><tbody><tr><td>{{ $session?->station_name }}</td><td>Session {{ $session?->reference }}<br>Connector {{ $session?->connector_external_id }} - {{ number_format($session?->energy_kwh ?? 0, 3) }} kWh</td><td class="right">{{ number_format((($session?->energy_kwh ?? 0) * ($session?->price_per_kwh_millimes ?? 0)) / 1000, 3) }} {{ $payment->currency }}</td></tr><tr><td>Session fee</td><td>{{ $session?->tariff_name ?? 'Applied tariff' }}</td><td class="right">{{ number_format(($session?->session_fee_millimes ?? 0) / 1000, 3) }} {{ $payment->currency }}</td></tr>@if(($session?->discount_millimes ?? 0) > 0)<tr><td>Plan discount</td><td>{{ $session?->charging_plan_name }}</td><td class="right">-{{ number_format($session->discount_millimes / 1000, 3) }} {{ $payment->currency }}</td></tr>@endif<tr class="total"><td colspan="2">Total</td><td class="right">{{ number_format($payment->amount_millimes / 1000, 3) }} {{ $payment->currency }}</td></tr></tbody></table>
<div class="note">This receipt records a transaction processed by the configured ChargeTrackr payment adapter. Keep the payment reference for operational support.</div><footer>Generated {{ $issuedAt }} - ChargeTrackr</footer>
</body></html>
